name: build and test feature branch
on: #Eventos
    push:
        branches:
            - feature/*
jobs: #Construir el ambiente
    build-feature:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: pull and chekout form git repository

              run: | 
                echo "pulling and cheking out form git repository"

            - name: setupp java 17
              uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '17'

            - name: build with maven
              run: |
                mvnw clean install
                echo "building with maven"
            